version: '3'

services:
  database:
    container_name: database
    image: postgres:15
    ports:
      - 15432:5432
    volumes:
      - keycloak_db:/var/lib/postgresql/data
    networks:
      - silom-network
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  keycloak:
    container_name: authentication
    image: quay.io/keycloak/keycloak:20.0.1
    depends_on:
      - database
    ports:
      - 18080:8080
    networks:
      - silom-network
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://database/keycloak
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - 'start --hostname-strict=false --hostname-strict-https=false --proxy=edge'

networks:
  silom-network:
    external: true

volumes:
  keycloak_db:
    external: true
